version: "3.7"

services:
  # react project
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && npm run dev:node"
    volumes:
      - ./frontend:/app
    depends_on:
      - app
      - db
    ports:
      - 8888:8888
    networks:
      - laravel

  # image project
  app:
    build:
      context: ./backend/app_laravel
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend/app_laravel:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./backend/app_laravel:/var/www
      - ./backend/app_laravel/docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./backend/app_laravel/.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
